//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class SimulateStepsResult : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/SimulateSteps";
        public override string RosMessageName => k_RosMessageName;

        public ResultMsg result;
        //  Calling with simulation unpaused will return OPERATION_FAILED and error message.

        public SimulateStepsResult()
        {
            this.result = new ResultMsg();
        }

        public SimulateStepsResult(ResultMsg result)
        {
            this.result = result;
        }

        public static SimulateStepsResult Deserialize(MessageDeserializer deserializer) => new SimulateStepsResult(deserializer);

        private SimulateStepsResult(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "SimulateStepsResult: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
