//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class SimulateStepsFeedback : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/SimulateSteps";
        public override string RosMessageName => k_RosMessageName;

        public ulong completed_steps;
        //  number of completed steps in this action so far.
        public ulong remaining_steps;
        //  number of steps remaining to be completed in this action.

        public SimulateStepsFeedback()
        {
            this.completed_steps = 0;
            this.remaining_steps = 0;
        }

        public SimulateStepsFeedback(ulong completed_steps, ulong remaining_steps)
        {
            this.completed_steps = completed_steps;
            this.remaining_steps = remaining_steps;
        }

        public static SimulateStepsFeedback Deserialize(MessageDeserializer deserializer) => new SimulateStepsFeedback(deserializer);

        private SimulateStepsFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.completed_steps);
            deserializer.Read(out this.remaining_steps);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.completed_steps);
            serializer.Write(this.remaining_steps);
        }

        public override string ToString()
        {
            return "SimulateStepsFeedback: " +
            "\ncompleted_steps: " + completed_steps.ToString() +
            "\nremaining_steps: " + remaining_steps.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
