//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class SimulateStepsGoal : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/SimulateSteps";
        public override string RosMessageName => k_RosMessageName;

        //  Assuming the simulation is paused, simulate a finite number of steps and return to paused state. 
        //  The action returns feedback after each complete step.
        //  For a service alternative, see StepSimulation, which often makes more sense when doing a single step (steps = 1).
        //  Support for this interface is indicated through the STEP_SIMULATION_ACTION value in GetSimulationFeatures.
        public ulong steps;
        //  Action goal: step through the simulation loop this many times.

        public SimulateStepsGoal()
        {
            this.steps = 0;
        }

        public SimulateStepsGoal(ulong steps)
        {
            this.steps = steps;
        }

        public static SimulateStepsGoal Deserialize(MessageDeserializer deserializer) => new SimulateStepsGoal(deserializer);

        private SimulateStepsGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.steps);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.steps);
        }

        public override string ToString()
        {
            return "SimulateStepsGoal: " +
            "\nsteps: " + steps.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
