//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class EntityInfoMsg : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/EntityInfo";
        public override string RosMessageName => k_RosMessageName;

        //  Entity type and additional information
        public EntityCategoryMsg category;
        //  Major category for the entity. Extra entity type distinction can be made through tags.
        public string description;
        //  optional: verbose, human-readable description of the entity.
        public string[] tags;
        //  optional: tags which are useful for filtering and categorizing entities further.

        public EntityInfoMsg()
        {
            this.category = new EntityCategoryMsg();
            this.description = "";
            this.tags = new string[0];
        }

        public EntityInfoMsg(EntityCategoryMsg category, string description, string[] tags)
        {
            this.category = category;
            this.description = description;
            this.tags = tags;
        }

        public static EntityInfoMsg Deserialize(MessageDeserializer deserializer) => new EntityInfoMsg(deserializer);

        private EntityInfoMsg(MessageDeserializer deserializer)
        {
            this.category = EntityCategoryMsg.Deserialize(deserializer);
            deserializer.Read(out this.description);
            deserializer.Read(out this.tags, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.category);
            serializer.Write(this.description);
            serializer.WriteLength(this.tags);
            serializer.Write(this.tags);
        }

        public override string ToString()
        {
            return "EntityInfoMsg: " +
            "\ncategory: " + category.ToString() +
            "\ndescription: " + description.ToString() +
            "\ntags: " + System.String.Join(", ", tags.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
