//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class EntityCategoryMsg : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/EntityCategory";
        public override string RosMessageName => k_RosMessageName;

        //  Entity major category, which often warrants a specific way to handle such entity, e.g. when handling humans
        //  or mapping persistence for dynamic vs static objects.
        public const byte CATEGORY_OBJECT = 0; //  Generic or unspecified type.
        public const byte CATEGORY_ROBOT = 1; //  A broad category for mobile robots, arms, drones etc.,
        //  usually with ROS 2 interfaces.
        public const byte CATEGORY_HUMAN = 2; //  Simulated humans, e.g. pedestrians, warehouse workers.
        //  Compared to CATEGORY_DYNAMIC_OBJECT, humans are often expected to be treated
        //  exceptionally in regards to safety constraints.
        public const byte CATEGORY_DYNAMIC_OBJECT = 4; //  Vehicles, animals, mobile obstacles, typically to present a detection and
        //  tracking challenge, such as when simulation is used to test robot perception
        //  or navigation stack.
        public const byte CATEGORY_STATIC_OBJECT = 5; //  Any object which is static, e.g. not supposed to change its pose
        //  unless by means of SetEntityState.
        public byte category;

        public EntityCategoryMsg()
        {
            this.category = 0;
        }

        public EntityCategoryMsg(byte category)
        {
            this.category = category;
        }

        public static EntityCategoryMsg Deserialize(MessageDeserializer deserializer) => new EntityCategoryMsg(deserializer);

        private EntityCategoryMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.category);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.category);
        }

        public override string ToString()
        {
            return "EntityCategoryMsg: " +
            "\ncategory: " + category.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
