//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class ResourceMsg : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/Resource";
        public override string RosMessageName => k_RosMessageName;

        //  This message is used to specify a resource, either by a URI or by its string content.
        public string uri;
        //  If uri field is empty, resource_string must not be empty.
        public string resource_string;
        //  An entity definition file passed as a string, only used if uri is empty.
        //  If uri field is not empty, resource_string field will be ignored.
        //  Simulators may support spawning from a file generated on the fly (e.g. XACRO).

        public ResourceMsg()
        {
            this.uri = "";
            this.resource_string = "";
        }

        public ResourceMsg(string uri, string resource_string)
        {
            this.uri = uri;
            this.resource_string = resource_string;
        }

        public static ResourceMsg Deserialize(MessageDeserializer deserializer) => new ResourceMsg(deserializer);

        private ResourceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.uri);
            deserializer.Read(out this.resource_string);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.uri);
            serializer.Write(this.resource_string);
        }

        public override string ToString()
        {
            return "ResourceMsg: " +
            "\nuri: " + uri.ToString() +
            "\nresource_string: " + resource_string.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
