//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class SpawnableMsg : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/Spawnable";
        public override string RosMessageName => k_RosMessageName;

        //  Robot or other object which can be spawned in simulation runtime.
        public string uri;
        //  URI which will be accepted by SpawnEntity service.
        public string description;
        //  Optional description for the user, e.g. "robot X with sensors A,B,C".
        public BoundsMsg spawn_bounds;
        //  Optional spawn area bounds which fully encompass this object.

        public SpawnableMsg()
        {
            this.uri = "";
            this.description = "";
            this.spawn_bounds = new BoundsMsg();
        }

        public SpawnableMsg(string uri, string description, BoundsMsg spawn_bounds)
        {
            this.uri = uri;
            this.description = description;
            this.spawn_bounds = spawn_bounds;
        }

        public static SpawnableMsg Deserialize(MessageDeserializer deserializer) => new SpawnableMsg(deserializer);

        private SpawnableMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.uri);
            deserializer.Read(out this.description);
            this.spawn_bounds = BoundsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.uri);
            serializer.Write(this.description);
            serializer.Write(this.spawn_bounds);
        }

        public override string ToString()
        {
            return "SpawnableMsg: " +
            "\nuri: " + uri.ToString() +
            "\ndescription: " + description.ToString() +
            "\nspawn_bounds: " + spawn_bounds.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
