//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class SpawnEntityMsg : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/SpawnEntity";
        public override string RosMessageName => k_RosMessageName;

        //  Information about spawning an individual entity.
        public string name;
        //  A name to give to the spawned entity.
        //  If empty, the name field in the URI file or resource_string will be used,
        //  if supported and not empty (e.g. "name" field in SDFormat, URDF).
        //  If the name is still empty or not unique (as determined by the simulator),
        //  the service returns a generated name in the entity_name response field if the
        //  allow_renaming field is set to true. Otherwise, the service call fails and an
        //  error is returned.
        public bool allow_renaming;
        //  Determines whether the spawning succeeds with a non-unique name.
        //  If it is set to true, the user should always check entity_name response field
        //  and use it for any further interactions.
        public ResourceMsg entity_resource;
        //  Resource such as SDFormat, URDF, USD or MJCF file, a native prefab, etc.
        //  Valid URIs can be determined by calling GetSpawnables first. 
        //  Check simulator format support via the spawn_formats field in GetSimulatorFeatures.
        //  Using resource_string is supported if GetSimulatorFeatures includes
        //  the SPAWNING_RESOURCE_STRING feature.
        public string entity_namespace;
        //  Spawn the entity with all its interfaces under this namespace.
        public Geometry.PoseStampedMsg initial_pose;
        //  Initial entity pose.
        //  The header contains a reference frame, which defaults to global "world" frame.
        //  This frame must be known to the simulator, e.g. of an object spawned earlier.
        //  The timestamp field in the header is ignored.

        public SpawnEntityMsg()
        {
            this.name = "";
            this.allow_renaming = false;
            this.entity_resource = new ResourceMsg();
            this.entity_namespace = "";
            this.initial_pose = new Geometry.PoseStampedMsg();
        }

        public SpawnEntityMsg(string name, bool allow_renaming, ResourceMsg entity_resource, string entity_namespace, Geometry.PoseStampedMsg initial_pose)
        {
            this.name = name;
            this.allow_renaming = allow_renaming;
            this.entity_resource = entity_resource;
            this.entity_namespace = entity_namespace;
            this.initial_pose = initial_pose;
        }

        public static SpawnEntityMsg Deserialize(MessageDeserializer deserializer) => new SpawnEntityMsg(deserializer);

        private SpawnEntityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.allow_renaming);
            this.entity_resource = ResourceMsg.Deserialize(deserializer);
            deserializer.Read(out this.entity_namespace);
            this.initial_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.allow_renaming);
            serializer.Write(this.entity_resource);
            serializer.Write(this.entity_namespace);
            serializer.Write(this.initial_pose);
        }

        public override string ToString()
        {
            return "SpawnEntityMsg: " +
            "\nname: " + name.ToString() +
            "\nallow_renaming: " + allow_renaming.ToString() +
            "\nentity_resource: " + entity_resource.ToString() +
            "\nentity_namespace: " + entity_namespace.ToString() +
            "\ninitial_pose: " + initial_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
