//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class WorldResourceMsg : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/WorldResource";
        public override string RosMessageName => k_RosMessageName;

        //  World is a virtual environment in which the simulation happens.
        //  Worlds are also known as scenes or levels in some simulators.
        //  Depending on the world format, loading of a world might be associated with changes
        //  in certain parameters, including physics settings such as gravity.
        //  World resources may be defined in standard or simulation-specific formats,
        //  and, depending on the simulator, loaded from local or remote repositories.
        public string name;
        //  World name, which is not necessarily unique.
        public ResourceMsg world_resource;
        //  The resource for the world to be loaded.
        public string description;
        //  Optional custom description of the world
        public string[] tags;
        //  Optional tags describing the world (e.g., "indoor", "outdoor", "warehouse")

        public WorldResourceMsg()
        {
            this.name = "";
            this.world_resource = new ResourceMsg();
            this.description = "";
            this.tags = new string[0];
        }

        public WorldResourceMsg(string name, ResourceMsg world_resource, string description, string[] tags)
        {
            this.name = name;
            this.world_resource = world_resource;
            this.description = description;
            this.tags = tags;
        }

        public static WorldResourceMsg Deserialize(MessageDeserializer deserializer) => new WorldResourceMsg(deserializer);

        private WorldResourceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            this.world_resource = ResourceMsg.Deserialize(deserializer);
            deserializer.Read(out this.description);
            deserializer.Read(out this.tags, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.world_resource);
            serializer.Write(this.description);
            serializer.WriteLength(this.tags);
            serializer.Write(this.tags);
        }

        public override string ToString()
        {
            return "WorldResourceMsg: " +
            "\nname: " + name.ToString() +
            "\nworld_resource: " + world_resource.ToString() +
            "\ndescription: " + description.ToString() +
            "\ntags: " + System.String.Join(", ", tags.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
