//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class DeleteEntityRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/DeleteEntity";
        public override string RosMessageName => k_RosMessageName;

        //  Remove an entity (a robot, other object) from the simulation.
        //  Support for this interface is indicated through the DELETING value in GetSimulationFeatures.
        public string entity;
        //  Entity identified by its unique name with a namespace,
        //  as returned by SpawnEntity or GetEntities.

        public DeleteEntityRequest()
        {
            this.entity = "";
        }

        public DeleteEntityRequest(string entity)
        {
            this.entity = entity;
        }

        public static DeleteEntityRequest Deserialize(MessageDeserializer deserializer) => new DeleteEntityRequest(deserializer);

        private DeleteEntityRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.entity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.entity);
        }

        public override string ToString()
        {
            return "DeleteEntityRequest: " +
            "\nentity: " + entity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
