//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetAvailableWorldsRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetAvailableWorlds";
        public override string RosMessageName => k_RosMessageName;

        //  Return a list of available world resources which can be used with LoadWorld.
        //  Support for this interface is indicated through the AVAILABLE_WORLDS value in GetSimulatorFeatures.
        //  By default, a simulator will search its default local and online sources. If some
        //  default sources can't be accessed (e.g. due to connectivity issues), the
        //  DEFAULT_SOURCES_FAILED error result code will be returned.
        public string[] additional_sources;
        //  Optional field for additional sources (local or remote) to search, 
        //  specified as standard URIs if possible.
        public TagsFilterMsg filter;
        //  Only get worlds with tags matching the filter. The filter is optional and matches everything by default.
        //  This feature is supported if WORLD_TAGS feature is included in output of GetSimulatorFeatures.
        public bool offline_only;
        //  If true, only offline/local sources should be searched. Defaults to false.
        public bool continue_on_error;
        //  If true, the simulator will continue to search sources even if some fail.
        //  The service will return success if any source yielded worlds. Defaults to false.

        public GetAvailableWorldsRequest()
        {
            this.additional_sources = new string[0];
            this.filter = new TagsFilterMsg();
            this.offline_only = false;
            this.continue_on_error = false;
        }

        public GetAvailableWorldsRequest(string[] additional_sources, TagsFilterMsg filter, bool offline_only, bool continue_on_error)
        {
            this.additional_sources = additional_sources;
            this.filter = filter;
            this.offline_only = offline_only;
            this.continue_on_error = continue_on_error;
        }

        public static GetAvailableWorldsRequest Deserialize(MessageDeserializer deserializer) => new GetAvailableWorldsRequest(deserializer);

        private GetAvailableWorldsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.additional_sources, deserializer.ReadLength());
            this.filter = TagsFilterMsg.Deserialize(deserializer);
            deserializer.Read(out this.offline_only);
            deserializer.Read(out this.continue_on_error);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.additional_sources);
            serializer.Write(this.additional_sources);
            serializer.Write(this.filter);
            serializer.Write(this.offline_only);
            serializer.Write(this.continue_on_error);
        }

        public override string ToString()
        {
            return "GetAvailableWorldsRequest: " +
            "\nadditional_sources: " + System.String.Join(", ", additional_sources.ToList()) +
            "\nfilter: " + filter.ToString() +
            "\noffline_only: " + offline_only.ToString() +
            "\ncontinue_on_error: " + continue_on_error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
