//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetAvailableWorldsResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetAvailableWorlds";
        public override string RosMessageName => k_RosMessageName;

        public const byte DEFAULT_SOURCES_FAILED = 101; //  Some default sources could not be accessed.
        public ResultMsg result;
        //  Standard result message. A specific result code should be used if some sources were not accessible.
        public WorldResourceMsg[] worlds;
        //  Available world resources.

        public GetAvailableWorldsResponse()
        {
            this.result = new ResultMsg();
            this.worlds = new WorldResourceMsg[0];
        }

        public GetAvailableWorldsResponse(ResultMsg result, WorldResourceMsg[] worlds)
        {
            this.result = result;
            this.worlds = worlds;
        }

        public static GetAvailableWorldsResponse Deserialize(MessageDeserializer deserializer) => new GetAvailableWorldsResponse(deserializer);

        private GetAvailableWorldsResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
            deserializer.Read(out this.worlds, WorldResourceMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.WriteLength(this.worlds);
            serializer.Write(this.worlds);
        }

        public override string ToString()
        {
            return "GetAvailableWorldsResponse: " +
            "\nresult: " + result.ToString() +
            "\nworlds: " + System.String.Join(", ", worlds.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
