//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetCurrentWorldRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetCurrentWorld";
        public override string RosMessageName => k_RosMessageName;

        //  Get information about the currently loaded world in the simulation.
        //  Support for this interface is indicated through the WORLD_INFO_GETTING value in GetSimulatorFeatures.

        public GetCurrentWorldRequest()
        {
        }
        public static GetCurrentWorldRequest Deserialize(MessageDeserializer deserializer) => new GetCurrentWorldRequest(deserializer);

        private GetCurrentWorldRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetCurrentWorldRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
