//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetCurrentWorldResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetCurrentWorld";
        public override string RosMessageName => k_RosMessageName;

        public const byte NO_WORLD_LOADED = 101; //  No world is loaded at the moment.
        public ResultMsg result;
        //  Standard result message
        public WorldResourceMsg world;
        //  Information about the currently loaded world. Only valid if result is RESULT_OK.

        public GetCurrentWorldResponse()
        {
            this.result = new ResultMsg();
            this.world = new WorldResourceMsg();
        }

        public GetCurrentWorldResponse(ResultMsg result, WorldResourceMsg world)
        {
            this.result = result;
            this.world = world;
        }

        public static GetCurrentWorldResponse Deserialize(MessageDeserializer deserializer) => new GetCurrentWorldResponse(deserializer);

        private GetCurrentWorldResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
            this.world = WorldResourceMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.world);
        }

        public override string ToString()
        {
            return "GetCurrentWorldResponse: " +
            "\nresult: " + result.ToString() +
            "\nworld: " + world.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
