//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetEntityInfoResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetEntityInfo";
        public override string RosMessageName => k_RosMessageName;

        public ResultMsg result;
        public EntityInfoMsg info;
        //  Only valid if result.result_code is OK.

        public GetEntityInfoResponse()
        {
            this.result = new ResultMsg();
            this.info = new EntityInfoMsg();
        }

        public GetEntityInfoResponse(ResultMsg result, EntityInfoMsg info)
        {
            this.result = result;
            this.info = info;
        }

        public static GetEntityInfoResponse Deserialize(MessageDeserializer deserializer) => new GetEntityInfoResponse(deserializer);

        private GetEntityInfoResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
            this.info = EntityInfoMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.info);
        }

        public override string ToString()
        {
            return "GetEntityInfoResponse: " +
            "\nresult: " + result.ToString() +
            "\ninfo: " + info.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
