//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetEntityStateResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetEntityState";
        public override string RosMessageName => k_RosMessageName;

        public ResultMsg result;
        public EntityStateMsg state;
        //  Entity ground truth state. Valid when result.result = OK.

        public GetEntityStateResponse()
        {
            this.result = new ResultMsg();
            this.state = new EntityStateMsg();
        }

        public GetEntityStateResponse(ResultMsg result, EntityStateMsg state)
        {
            this.result = result;
            this.state = state;
        }

        public static GetEntityStateResponse Deserialize(MessageDeserializer deserializer) => new GetEntityStateResponse(deserializer);

        private GetEntityStateResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
            this.state = EntityStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "GetEntityStateResponse: " +
            "\nresult: " + result.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
