//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetEntityStateRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetEntityState";
        public override string RosMessageName => k_RosMessageName;

        //  Get state of an entity.
        //  Support for this interface is indicated through the ENTITY_STATE_GETTING value in GetSimulationFeatures.
        public string entity;
        //  Entity identified by its unique name as returned by GetEntities / SpawnEntity.

        public GetEntityStateRequest()
        {
            this.entity = "";
        }

        public GetEntityStateRequest(string entity)
        {
            this.entity = entity;
        }

        public static GetEntityStateRequest Deserialize(MessageDeserializer deserializer) => new GetEntityStateRequest(deserializer);

        private GetEntityStateRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.entity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.entity);
        }

        public override string ToString()
        {
            return "GetEntityStateRequest: " +
            "\nentity: " + entity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
