//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetEntityInfoRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetEntityInfo";
        public override string RosMessageName => k_RosMessageName;

        //  Get type and other information about an entity.
        //  Support for this interface is indicated through the ENTITY_INFO_GETTING value in GetSimulationFeatures.
        public string entity;
        //  Entity identified by its unique name as returned by GetEntities.

        public GetEntityInfoRequest()
        {
            this.entity = "";
        }

        public GetEntityInfoRequest(string entity)
        {
            this.entity = entity;
        }

        public static GetEntityInfoRequest Deserialize(MessageDeserializer deserializer) => new GetEntityInfoRequest(deserializer);

        private GetEntityInfoRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.entity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.entity);
        }

        public override string ToString()
        {
            return "GetEntityInfoRequest: " +
            "\nentity: " + entity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
