//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetEntityBoundsRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetEntityBounds";
        public override string RosMessageName => k_RosMessageName;

        //  Get geometrical bounds for entity. This feature is available if GetSimulatorFeatures includes ENTITY_BOUNDS feature.
        //  Support for this interface is indicated through the ENTITY_BOUNDS value in GetSimulationFeatures.
        public string entity;
        //  Entity identified by its unique name as returned by GetEntities / SpawnEntity.

        public GetEntityBoundsRequest()
        {
            this.entity = "";
        }

        public GetEntityBoundsRequest(string entity)
        {
            this.entity = entity;
        }

        public static GetEntityBoundsRequest Deserialize(MessageDeserializer deserializer) => new GetEntityBoundsRequest(deserializer);

        private GetEntityBoundsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.entity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.entity);
        }

        public override string ToString()
        {
            return "GetEntityBoundsRequest: " +
            "\nentity: " + entity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
