//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetEntityBoundsResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetEntityBounds";
        public override string RosMessageName => k_RosMessageName;

        public ResultMsg result;
        public BoundsMsg bounds;
        //  Entity bounds. Only valid if result.result_code is OK.
        //  Bounds with TYPE_BOX should be returned, unless there is a configuration
        //  parameter for the simulator to control the type and it is set otherwise.

        public GetEntityBoundsResponse()
        {
            this.result = new ResultMsg();
            this.bounds = new BoundsMsg();
        }

        public GetEntityBoundsResponse(ResultMsg result, BoundsMsg bounds)
        {
            this.result = result;
            this.bounds = bounds;
        }

        public static GetEntityBoundsResponse Deserialize(MessageDeserializer deserializer) => new GetEntityBoundsResponse(deserializer);

        private GetEntityBoundsResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
            this.bounds = BoundsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.bounds);
        }

        public override string ToString()
        {
            return "GetEntityBoundsResponse: " +
            "\nresult: " + result.ToString() +
            "\nbounds: " + bounds.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
