//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetEntitiesResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetEntities";
        public override string RosMessageName => k_RosMessageName;

        public ResultMsg result;
        public string[] entities;
        //  Unique names of all entities matching the filters.

        public GetEntitiesResponse()
        {
            this.result = new ResultMsg();
            this.entities = new string[0];
        }

        public GetEntitiesResponse(ResultMsg result, string[] entities)
        {
            this.result = result;
            this.entities = entities;
        }

        public static GetEntitiesResponse Deserialize(MessageDeserializer deserializer) => new GetEntitiesResponse(deserializer);

        private GetEntitiesResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
            deserializer.Read(out this.entities, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.WriteLength(this.entities);
            serializer.Write(this.entities);
        }

        public override string ToString()
        {
            return "GetEntitiesResponse: " +
            "\nresult: " + result.ToString() +
            "\nentities: " + System.String.Join(", ", entities.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
