//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetEntitiesRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetEntities";
        public override string RosMessageName => k_RosMessageName;

        //  Get objects in the scene which can be interacted with, e.g. with using SetEntityState.
        //  You can get further information about entities through GetEntityInfo and GetEntityState services.
        //  There is also a GetEntitiesStates service if you would like to get state for each entity.
        public EntityFiltersMsg filters;
        //  Optional filters for the query, including name, category, tags,
        //  and overlap filters.

        public GetEntitiesRequest()
        {
            this.filters = new EntityFiltersMsg();
        }

        public GetEntitiesRequest(EntityFiltersMsg filters)
        {
            this.filters = filters;
        }

        public static GetEntitiesRequest Deserialize(MessageDeserializer deserializer) => new GetEntitiesRequest(deserializer);

        private GetEntitiesRequest(MessageDeserializer deserializer)
        {
            this.filters = EntityFiltersMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.filters);
        }

        public override string ToString()
        {
            return "GetEntitiesRequest: " +
            "\nfilters: " + filters.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
