//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetNamedPoseBoundsResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetNamedPoseBounds";
        public override string RosMessageName => k_RosMessageName;

        public ResultMsg result;
        public BoundsMsg bounds;
        //  bounds for the named pose.

        public GetNamedPoseBoundsResponse()
        {
            this.result = new ResultMsg();
            this.bounds = new BoundsMsg();
        }

        public GetNamedPoseBoundsResponse(ResultMsg result, BoundsMsg bounds)
        {
            this.result = result;
            this.bounds = bounds;
        }

        public static GetNamedPoseBoundsResponse Deserialize(MessageDeserializer deserializer) => new GetNamedPoseBoundsResponse(deserializer);

        private GetNamedPoseBoundsResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
            this.bounds = BoundsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.bounds);
        }

        public override string ToString()
        {
            return "GetNamedPoseBoundsResponse: " +
            "\nresult: " + result.ToString() +
            "\nbounds: " + bounds.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
