//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetNamedPosesRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetNamedPoses";
        public override string RosMessageName => k_RosMessageName;

        //  Get predefined poses which are convenient to for spawning, navigation goals etc.
        //  Support for this interface is indicated through the NAMED_POSES value in GetSimulationFeatures.
        public TagsFilterMsg tags;
        //  Tags filter to apply. Only named poses with matching tags field
        //  will be returned. Can be empty (see TagsFilter).

        public GetNamedPosesRequest()
        {
            this.tags = new TagsFilterMsg();
        }

        public GetNamedPosesRequest(TagsFilterMsg tags)
        {
            this.tags = tags;
        }

        public static GetNamedPosesRequest Deserialize(MessageDeserializer deserializer) => new GetNamedPosesRequest(deserializer);

        private GetNamedPosesRequest(MessageDeserializer deserializer)
        {
            this.tags = TagsFilterMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tags);
        }

        public override string ToString()
        {
            return "GetNamedPosesRequest: " +
            "\ntags: " + tags.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
