//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetNamedPosesResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetNamedPoses";
        public override string RosMessageName => k_RosMessageName;

        public ResultMsg result;
        public NamedPoseMsg[] poses;
        //  A list of predefined poses, which may be empty.

        public GetNamedPosesResponse()
        {
            this.result = new ResultMsg();
            this.poses = new NamedPoseMsg[0];
        }

        public GetNamedPosesResponse(ResultMsg result, NamedPoseMsg[] poses)
        {
            this.result = result;
            this.poses = poses;
        }

        public static GetNamedPosesResponse Deserialize(MessageDeserializer deserializer) => new GetNamedPosesResponse(deserializer);

        private GetNamedPosesResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
            deserializer.Read(out this.poses, NamedPoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.WriteLength(this.poses);
            serializer.Write(this.poses);
        }

        public override string ToString()
        {
            return "GetNamedPosesResponse: " +
            "\nresult: " + result.ToString() +
            "\nposes: " + System.String.Join(", ", poses.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
