//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetNamedPoseBoundsRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetNamedPoseBounds";
        public override string RosMessageName => k_RosMessageName;

        //  Get bounds for the named pose. This feature is available if GetSimulatorFeatures includes POSE_BOUNDS feature.
        //  Support for this interface is indicated through the POSE_BOUNDS value in GetSimulationFeatures.
        public string name;
        //  unique name (as returned from GetNamedPoses).

        public GetNamedPoseBoundsRequest()
        {
            this.name = "";
        }

        public GetNamedPoseBoundsRequest(string name)
        {
            this.name = name;
        }

        public static GetNamedPoseBoundsRequest Deserialize(MessageDeserializer deserializer) => new GetNamedPoseBoundsRequest(deserializer);

        private GetNamedPoseBoundsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "GetNamedPoseBoundsRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
