//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetSpawnablesResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetSpawnables";
        public override string RosMessageName => k_RosMessageName;

        public ResultMsg result;
        public SpawnableMsg[] spawnables;
        //  Spawnable objects with URI and additional information.

        public GetSpawnablesResponse()
        {
            this.result = new ResultMsg();
            this.spawnables = new SpawnableMsg[0];
        }

        public GetSpawnablesResponse(ResultMsg result, SpawnableMsg[] spawnables)
        {
            this.result = result;
            this.spawnables = spawnables;
        }

        public static GetSpawnablesResponse Deserialize(MessageDeserializer deserializer) => new GetSpawnablesResponse(deserializer);

        private GetSpawnablesResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
            deserializer.Read(out this.spawnables, SpawnableMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.WriteLength(this.spawnables);
            serializer.Write(this.spawnables);
        }

        public override string ToString()
        {
            return "GetSpawnablesResponse: " +
            "\nresult: " + result.ToString() +
            "\nspawnables: " + System.String.Join(", ", spawnables.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
