//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetSimulationStateResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetSimulationState";
        public override string RosMessageName => k_RosMessageName;

        public SimulationStateMsg state;
        //  Current state of the simulation.
        public ResultMsg result;

        public GetSimulationStateResponse()
        {
            this.state = new SimulationStateMsg();
            this.result = new ResultMsg();
        }

        public GetSimulationStateResponse(SimulationStateMsg state, ResultMsg result)
        {
            this.state = state;
            this.result = result;
        }

        public static GetSimulationStateResponse Deserialize(MessageDeserializer deserializer) => new GetSimulationStateResponse(deserializer);

        private GetSimulationStateResponse(MessageDeserializer deserializer)
        {
            this.state = SimulationStateMsg.Deserialize(deserializer);
            this.result = ResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "GetSimulationStateResponse: " +
            "\nstate: " + state.ToString() +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
