//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetSimulatorFeaturesRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetSimulatorFeatures";
        public override string RosMessageName => k_RosMessageName;

        //  Get a list of features supported by the simulator.
        //  Simulators adhering to the standard need to implement at least this interface.

        public GetSimulatorFeaturesRequest()
        {
        }
        public static GetSimulatorFeaturesRequest Deserialize(MessageDeserializer deserializer) => new GetSimulatorFeaturesRequest(deserializer);

        private GetSimulatorFeaturesRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetSimulatorFeaturesRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
