//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetSimulatorFeaturesResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetSimulatorFeatures";
        public override string RosMessageName => k_RosMessageName;

        public SimulatorFeaturesMsg features;

        public GetSimulatorFeaturesResponse()
        {
            this.features = new SimulatorFeaturesMsg();
        }

        public GetSimulatorFeaturesResponse(SimulatorFeaturesMsg features)
        {
            this.features = features;
        }

        public static GetSimulatorFeaturesResponse Deserialize(MessageDeserializer deserializer) => new GetSimulatorFeaturesResponse(deserializer);

        private GetSimulatorFeaturesResponse(MessageDeserializer deserializer)
        {
            this.features = SimulatorFeaturesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.features);
        }

        public override string ToString()
        {
            return "GetSimulatorFeaturesResponse: " +
            "\nfeatures: " + features.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
