//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class GetSimulationStateRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/GetSimulationState";
        public override string RosMessageName => k_RosMessageName;

        //  Gets the simulation state (paused, playing, stopped)
        //  Support for this interface is indicated through the SIMULATION_STATE_GETTING value in GetSimulationFeatures.

        public GetSimulationStateRequest()
        {
        }
        public static GetSimulationStateRequest Deserialize(MessageDeserializer deserializer) => new GetSimulationStateRequest(deserializer);

        private GetSimulationStateRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetSimulationStateRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
