//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class LoadWorldResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/LoadWorld";
        public override string RosMessageName => k_RosMessageName;

        public const byte UNSUPPORTED_FORMAT = 101; //  Format for uri or resource string is unsupported.
        public const byte NO_RESOURCE = 102; //  Both uri and resource string are empty.
        public const byte RESOURCE_PARSE_ERROR = 103; //  Resource file or string failed to parse.
        public const byte MISSING_ASSETS = 104; //  At least one of resource assets (such as meshes) was not found.
        public const byte UNSUPPORTED_ASSETS = 105; //  At least one of resource assets (such as meshes) is not supported.
        public const byte UNSUPPORTED_ELEMENTS = 106; //  At least one of world definition elements such as format tags is unsupported.
        public ResultMsg result;
        //  Standard result message
        public WorldResourceMsg world;
        //  Information about the loaded world. Only valid if result is RESULT_OK.

        public LoadWorldResponse()
        {
            this.result = new ResultMsg();
            this.world = new WorldResourceMsg();
        }

        public LoadWorldResponse(ResultMsg result, WorldResourceMsg world)
        {
            this.result = result;
            this.world = world;
        }

        public static LoadWorldResponse Deserialize(MessageDeserializer deserializer) => new LoadWorldResponse(deserializer);

        private LoadWorldResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
            this.world = WorldResourceMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.world);
        }

        public override string ToString()
        {
            return "LoadWorldResponse: " +
            "\nresult: " + result.ToString() +
            "\nworld: " + world.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
