//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class LoadWorldRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/LoadWorld";
        public override string RosMessageName => k_RosMessageName;

        //  Load a simulation world from a file or resource.
        //  This means clearing the current scene (removing all entities), loading the new world and setting the simulation to the stopped state.
        //  Support for this interface is indicated through the WORLD_LOADING value in GetSimulatorFeatures.
        //  resource_string field support is indicated through the WORLD_RESOURCE_STRING value in GetSimulatorFeatures.
        //  Currently loaded worlds will be unloaded before attempting to load a new one.
        //  Any previously spawned entities will be removed. Once a world is loaded, simulation will be left in a Stopped state.
        public ResourceMsg world_resource;
        //  Resource such as SDF, USD, MJCF, or other simulator-native format world file or,
        //  Simulation world passed as a string. 
        public bool fail_on_unsupported_element;
        //  Fail on unsupported elements (such as SDFormat sub-tags). By default, such elements are ignored.
        public bool ignore_missing_or_unsupported_assets;
        //  Ignore missing or unsupported assets. By default, missing or unsupported assets result in failure.

        public LoadWorldRequest()
        {
            this.world_resource = new ResourceMsg();
            this.fail_on_unsupported_element = false;
            this.ignore_missing_or_unsupported_assets = false;
        }

        public LoadWorldRequest(ResourceMsg world_resource, bool fail_on_unsupported_element, bool ignore_missing_or_unsupported_assets)
        {
            this.world_resource = world_resource;
            this.fail_on_unsupported_element = fail_on_unsupported_element;
            this.ignore_missing_or_unsupported_assets = ignore_missing_or_unsupported_assets;
        }

        public static LoadWorldRequest Deserialize(MessageDeserializer deserializer) => new LoadWorldRequest(deserializer);

        private LoadWorldRequest(MessageDeserializer deserializer)
        {
            this.world_resource = ResourceMsg.Deserialize(deserializer);
            deserializer.Read(out this.fail_on_unsupported_element);
            deserializer.Read(out this.ignore_missing_or_unsupported_assets);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.world_resource);
            serializer.Write(this.fail_on_unsupported_element);
            serializer.Write(this.ignore_missing_or_unsupported_assets);
        }

        public override string ToString()
        {
            return "LoadWorldRequest: " +
            "\nworld_resource: " + world_resource.ToString() +
            "\nfail_on_unsupported_element: " + fail_on_unsupported_element.ToString() +
            "\nignore_missing_or_unsupported_assets: " + ignore_missing_or_unsupported_assets.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
