//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class ResetSimulationResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/ResetSimulation";
        public override string RosMessageName => k_RosMessageName;

        public ResultMsg result;

        public ResetSimulationResponse()
        {
            this.result = new ResultMsg();
        }

        public ResetSimulationResponse(ResultMsg result)
        {
            this.result = result;
        }

        public static ResetSimulationResponse Deserialize(MessageDeserializer deserializer) => new ResetSimulationResponse(deserializer);

        private ResetSimulationResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "ResetSimulationResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
