//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class SetEntityStateResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/SetEntityState";
        public override string RosMessageName => k_RosMessageName;

        public ResultMsg result;

        public SetEntityStateResponse()
        {
            this.result = new ResultMsg();
        }

        public SetEntityStateResponse(ResultMsg result)
        {
            this.result = result;
        }

        public static SetEntityStateResponse Deserialize(MessageDeserializer deserializer) => new SetEntityStateResponse(deserializer);

        private SetEntityStateResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "SetEntityStateResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
