//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class SetEntityInfoRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/SetEntityInfo";
        public override string RosMessageName => k_RosMessageName;

        //  Set type, tags and other information about an entity.
        //  Support for this interface is indicated through the ENTITY_INFO_SETTING value in GetSimulationFeatures.
        public string entity;
        //  Entity identified by its unique name as returned by GetEntities.
        public EntityInfoMsg info;
        //  EntityInfo to set to the entity, which will override its current values.

        public SetEntityInfoRequest()
        {
            this.entity = "";
            this.info = new EntityInfoMsg();
        }

        public SetEntityInfoRequest(string entity, EntityInfoMsg info)
        {
            this.entity = entity;
            this.info = info;
        }

        public static SetEntityInfoRequest Deserialize(MessageDeserializer deserializer) => new SetEntityInfoRequest(deserializer);

        private SetEntityInfoRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.entity);
            this.info = EntityInfoMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.entity);
            serializer.Write(this.info);
        }

        public override string ToString()
        {
            return "SetEntityInfoRequest: " +
            "\nentity: " + entity.ToString() +
            "\ninfo: " + info.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
