//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class SetSimulationStateRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/SetSimulationState";
        public override string RosMessageName => k_RosMessageName;

        //  Change the simulation state
        //  Support for this interface is indicated through the SIMULATION_STATE_SETTING value in GetSimulationFeatures.
        //  Support for setting STATE_PAUSED is determined by SIMULATION_STATE_PAUSE feature.
        public SimulationStateMsg state;
        //  Target state to set for the simulation.

        public SetSimulationStateRequest()
        {
            this.state = new SimulationStateMsg();
        }

        public SetSimulationStateRequest(SimulationStateMsg state)
        {
            this.state = state;
        }

        public static SetSimulationStateRequest Deserialize(MessageDeserializer deserializer) => new SetSimulationStateRequest(deserializer);

        private SetSimulationStateRequest(MessageDeserializer deserializer)
        {
            this.state = SimulationStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "SetSimulationStateRequest: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
