//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class SetSimulationStateResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/SetSimulationState";
        public override string RosMessageName => k_RosMessageName;

        public const byte ALREADY_IN_TARGET_STATE = 101; //  Additional result type for this call, which means simulation was already in
        //  the target state (e.g. was already stopped when STATE_STOPPED was requested).
        public const byte STATE_TRANSITION_ERROR = 102; //  The simulator failed to transition to the target state. This might happen
        //  especially with the transition to STATE_PLAYING from STATE_STOPPED.
        //  See result.error_message for details.
        public const byte INCORRECT_TRANSITION = 103; //  Incorrect transition (pausing when in stopped state).
        public ResultMsg result;

        public SetSimulationStateResponse()
        {
            this.result = new ResultMsg();
        }

        public SetSimulationStateResponse(ResultMsg result)
        {
            this.result = result;
        }

        public static SetSimulationStateResponse Deserialize(MessageDeserializer deserializer) => new SetSimulationStateResponse(deserializer);

        private SetSimulationStateResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "SetSimulationStateResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
