//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class SpawnEntitiesRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/SpawnEntities";
        public override string RosMessageName => k_RosMessageName;

        //  Spawn multiple entities (robots, objects) by name or URI.
        //  Support for this interface is indicated through the SPAWNING_ENTITIES value in GetSimulatorFeatures.
        public SpawnEntityMsg[] spawn_requests;
        //  List of spawn requests.

        public SpawnEntitiesRequest()
        {
            this.spawn_requests = new SpawnEntityMsg[0];
        }

        public SpawnEntitiesRequest(SpawnEntityMsg[] spawn_requests)
        {
            this.spawn_requests = spawn_requests;
        }

        public static SpawnEntitiesRequest Deserialize(MessageDeserializer deserializer) => new SpawnEntitiesRequest(deserializer);

        private SpawnEntitiesRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.spawn_requests, SpawnEntityMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.spawn_requests);
            serializer.Write(this.spawn_requests);
        }

        public override string ToString()
        {
            return "SpawnEntitiesRequest: " +
            "\nspawn_requests: " + System.String.Join(", ", spawn_requests.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
