//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class SpawnEntitiesResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/SpawnEntities";
        public override string RosMessageName => k_RosMessageName;

        //  Additional result.result_code values for this service. Check result.error_message for further details.
        public const byte ENTITIES_SPAWN_FAILED = 150; //  There was at least one failed spawn request. Check individual results in the `results`.
        public ResultMsg result;
        //  If one or more requests failed, it will give ENTITIES_SPAWN_FAILED otherwise RESULT_OK
        public SpawnResultMsg[] results;
        //  List of results for each spawn request.

        public SpawnEntitiesResponse()
        {
            this.result = new ResultMsg();
            this.results = new SpawnResultMsg[0];
        }

        public SpawnEntitiesResponse(ResultMsg result, SpawnResultMsg[] results)
        {
            this.result = result;
            this.results = results;
        }

        public static SpawnEntitiesResponse Deserialize(MessageDeserializer deserializer) => new SpawnEntitiesResponse(deserializer);

        private SpawnEntitiesResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
            deserializer.Read(out this.results, SpawnResultMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.WriteLength(this.results);
            serializer.Write(this.results);
        }

        public override string ToString()
        {
            return "SpawnEntitiesResponse: " +
            "\nresult: " + result.ToString() +
            "\nresults: " + System.String.Join(", ", results.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
