//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class StepSimulationResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/StepSimulation";
        public override string RosMessageName => k_RosMessageName;

        public ResultMsg result;
        //  Calling with simulation not paused will return RESULT_OPERATION_FAILED and error message.

        public StepSimulationResponse()
        {
            this.result = new ResultMsg();
        }

        public StepSimulationResponse(ResultMsg result)
        {
            this.result = result;
        }

        public static StepSimulationResponse Deserialize(MessageDeserializer deserializer) => new StepSimulationResponse(deserializer);

        private StepSimulationResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "StepSimulationResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
