//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class StepSimulationRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/StepSimulation";
        public override string RosMessageName => k_RosMessageName;

        //  Assuming the simulation is paused, simulate a finite number of steps and return to paused state.
        //  The service only returns once stepping is complete, which might take considerable time.
        //  There is an alternative in SimulateSteps action, which is worth considering for a multi-step interface.
        //  Support for this interface is indicated through the STEP_SIMULATION_SINGLE and STEP_SIMULATION_MULTIPLE values
        //  in GetSimulationFeatures, for steps = 1 and steps > 1 correspondingly.
        public ulong steps = 1; //  Step through the simulation loop this many times.

        public StepSimulationRequest()
        {
        }

        public StepSimulationRequest(ulong steps)
        {
            this.steps = steps;
        }

        public static StepSimulationRequest Deserialize(MessageDeserializer deserializer) => new StepSimulationRequest(deserializer);

        private StepSimulationRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.steps);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.steps);
        }

        public override string ToString()
        {
            return "StepSimulationRequest: " +
            "\nsteps: " + steps.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
