//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class UnloadWorldResponse : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/UnloadWorld";
        public override string RosMessageName => k_RosMessageName;

        public const byte NO_WORLD_LOADED = 101; //  No world is loaded at the moment.
        public ResultMsg result;
        //  Standard result message

        public UnloadWorldResponse()
        {
            this.result = new ResultMsg();
        }

        public UnloadWorldResponse(ResultMsg result)
        {
            this.result = result;
        }

        public static UnloadWorldResponse Deserialize(MessageDeserializer deserializer) => new UnloadWorldResponse(deserializer);

        private UnloadWorldResponse(MessageDeserializer deserializer)
        {
            this.result = ResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "UnloadWorldResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
