//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationInterfaces
{
    [Serializable]
    public class UnloadWorldRequest : Message
    {
        public const string k_RosMessageName = "simulation_interfaces/UnloadWorld";
        public override string RosMessageName => k_RosMessageName;

        //  Unload the current simulation world.
        //  Support for this interface is indicated through the WORLD_UNLOADING value in GetSimulatorFeatures.
        //  Any previously spawned entities will be removed.

        public UnloadWorldRequest()
        {
        }
        public static UnloadWorldRequest Deserialize(MessageDeserializer deserializer) => new UnloadWorldRequest(deserializer);

        private UnloadWorldRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "UnloadWorldRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
