//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gps
{
    [Serializable]
    public class GPSFixMsg : Message
    {
        public const string k_RosMessageName = "gps_msgs/GPSFix";
        public override string RosMessageName => k_RosMessageName;

        //  A more complete GPS fix to supplement sensor_msgs/NavSatFix.
        public const byte COVARIANCE_TYPE_UNKNOWN = 0;
        public const byte COVARIANCE_TYPE_APPROXIMATED = 1;
        public const byte COVARIANCE_TYPE_DIAGONAL_KNOWN = 2;
        public const byte COVARIANCE_TYPE_KNOWN = 3;
        public Std.HeaderMsg header;
        public GPSStatusMsg status;
        public double latitude;
        public double longitude;
        public double altitude;
        public double track;
        public double speed;
        public double climb;
        public double pitch;
        public double roll;
        public double dip;
        public double time;
        public double gdop;
        public double pdop;
        public double hdop;
        public double vdop;
        public double tdop;
        public double err;
        public double err_horz;
        public double err_vert;
        public double err_track;
        public double err_speed;
        public double err_climb;
        public double err_time;
        public double err_pitch;
        public double err_roll;
        public double err_dip;
        public double[] position_covariance;
        public byte position_covariance_type;

        public GPSFixMsg()
        {
            this.header = new Std.HeaderMsg();
            this.status = new GPSStatusMsg();
            this.latitude = 0.0;
            this.longitude = 0.0;
            this.altitude = 0.0;
            this.track = 0.0;
            this.speed = 0.0;
            this.climb = 0.0;
            this.pitch = 0.0;
            this.roll = 0.0;
            this.dip = 0.0;
            this.time = 0.0;
            this.gdop = 0.0;
            this.pdop = 0.0;
            this.hdop = 0.0;
            this.vdop = 0.0;
            this.tdop = 0.0;
            this.err = 0.0;
            this.err_horz = 0.0;
            this.err_vert = 0.0;
            this.err_track = 0.0;
            this.err_speed = 0.0;
            this.err_climb = 0.0;
            this.err_time = 0.0;
            this.err_pitch = 0.0;
            this.err_roll = 0.0;
            this.err_dip = 0.0;
            this.position_covariance = new double[9];
            this.position_covariance_type = 0;
        }

        public static GPSFixMsg Deserialize(MessageDeserializer deserializer) => new GPSFixMsg(deserializer);

        private GPSFixMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.status = GPSStatusMsg.Deserialize(deserializer);
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.longitude);
            deserializer.Read(out this.altitude);
            deserializer.Read(out this.track);
            deserializer.Read(out this.speed);
            deserializer.Read(out this.climb);
            deserializer.Read(out this.pitch);
            deserializer.Read(out this.roll);
            deserializer.Read(out this.dip);
            deserializer.Read(out this.time);
            deserializer.Read(out this.gdop);
            deserializer.Read(out this.pdop);
            deserializer.Read(out this.hdop);
            deserializer.Read(out this.vdop);
            deserializer.Read(out this.tdop);
            deserializer.Read(out this.err);
            deserializer.Read(out this.err_horz);
            deserializer.Read(out this.err_vert);
            deserializer.Read(out this.err_track);
            deserializer.Read(out this.err_speed);
            deserializer.Read(out this.err_climb);
            deserializer.Read(out this.err_time);
            deserializer.Read(out this.err_pitch);
            deserializer.Read(out this.err_roll);
            deserializer.Read(out this.err_dip);
            deserializer.Read(out this.position_covariance, sizeof(double), 9);
            deserializer.Read(out this.position_covariance_type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.status);
            serializer.Write(this.latitude);
            serializer.Write(this.longitude);
            serializer.Write(this.altitude);
            serializer.Write(this.track);
            serializer.Write(this.speed);
            serializer.Write(this.climb);
            serializer.Write(this.pitch);
            serializer.Write(this.roll);
            serializer.Write(this.dip);
            serializer.Write(this.time);
            serializer.Write(this.gdop);
            serializer.Write(this.pdop);
            serializer.Write(this.hdop);
            serializer.Write(this.vdop);
            serializer.Write(this.tdop);
            serializer.Write(this.err);
            serializer.Write(this.err_horz);
            serializer.Write(this.err_vert);
            serializer.Write(this.err_track);
            serializer.Write(this.err_speed);
            serializer.Write(this.err_climb);
            serializer.Write(this.err_time);
            serializer.Write(this.err_pitch);
            serializer.Write(this.err_roll);
            serializer.Write(this.err_dip);
            serializer.Write(this.position_covariance);
            serializer.Write(this.position_covariance_type);
        }

        public override string ToString()
        {
            return "GPSFixMsg";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
