//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gps
{
    [Serializable]
    public class GPSStatusMsg : Message
    {
        public const string k_RosMessageName = "gps_msgs/GPSStatus";
        public override string RosMessageName => k_RosMessageName;

        //  Satellite status, including the RTK grades NavSatFix cannot express.
        public const short STATUS_NO_FIX = -1;
        public const short STATUS_FIX = 0;
        public const short STATUS_SBAS_FIX = 1;
        public const short STATUS_GBAS_FIX = 2;
        public const short STATUS_DGPS_FIX = 18;
        public const short STATUS_RTK_FIX = 19;
        public const short STATUS_RTK_FLOAT = 20;
        public const short STATUS_WAAS_FIX = 33;
        public const ushort SOURCE_NONE = 0;
        public const ushort SOURCE_GPS = 1;
        public const ushort SOURCE_POINTS = 2;
        public const ushort SOURCE_DOPPLER = 4;
        public const ushort SOURCE_ALTIMETER = 8;
        public const ushort SOURCE_MAGNETIC = 16;
        public const ushort SOURCE_GYRO = 32;
        public const ushort SOURCE_ACCEL = 64;
        public Std.HeaderMsg header;
        public ushort satellites_used;
        public int[] satellite_used_prn;
        public ushort satellites_visible;
        public int[] satellite_visible_prn;
        public int[] satellite_visible_z;
        public int[] satellite_visible_azimuth;
        public int[] satellite_visible_snr;
        public short status;
        public ushort motion_source;
        public ushort orientation_source;
        public ushort position_source;

        public GPSStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.satellites_used = 0;
            this.satellite_used_prn = new int[0];
            this.satellites_visible = 0;
            this.satellite_visible_prn = new int[0];
            this.satellite_visible_z = new int[0];
            this.satellite_visible_azimuth = new int[0];
            this.satellite_visible_snr = new int[0];
            this.status = 0;
            this.motion_source = 0;
            this.orientation_source = 0;
            this.position_source = 0;
        }

        public static GPSStatusMsg Deserialize(MessageDeserializer deserializer) => new GPSStatusMsg(deserializer);

        private GPSStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.satellites_used);
            deserializer.Read(out this.satellite_used_prn, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.satellites_visible);
            deserializer.Read(out this.satellite_visible_prn, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.satellite_visible_z, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.satellite_visible_azimuth, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.satellite_visible_snr, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.status);
            deserializer.Read(out this.motion_source);
            deserializer.Read(out this.orientation_source);
            deserializer.Read(out this.position_source);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.satellites_used);
            serializer.WriteLength(this.satellite_used_prn);
            serializer.Write(this.satellite_used_prn);
            serializer.Write(this.satellites_visible);
            serializer.WriteLength(this.satellite_visible_prn);
            serializer.Write(this.satellite_visible_prn);
            serializer.WriteLength(this.satellite_visible_z);
            serializer.Write(this.satellite_visible_z);
            serializer.WriteLength(this.satellite_visible_azimuth);
            serializer.Write(this.satellite_visible_azimuth);
            serializer.WriteLength(this.satellite_visible_snr);
            serializer.Write(this.satellite_visible_snr);
            serializer.Write(this.status);
            serializer.Write(this.motion_source);
            serializer.Write(this.orientation_source);
            serializer.Write(this.position_source);
        }

        public override string ToString()
        {
            return "GPSStatusMsg";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
