//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nmea
{
    [Serializable]
    public class SentenceMsg : Message
    {
        public const string k_RosMessageName = "nmea_msgs/Sentence";
        public override string RosMessageName => k_RosMessageName;

        //  A single NMEA0183 sentence.

        public Std.HeaderMsg header;
        public string sentence;

        public SentenceMsg()
        {
            this.header = new Std.HeaderMsg();
            this.sentence = "";
        }

        public static SentenceMsg Deserialize(MessageDeserializer deserializer) => new SentenceMsg(deserializer);

        private SentenceMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.sentence);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.sentence);
        }

        public override string ToString()
        {
            return "SentenceMsg";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
