//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationExtraInterfaces
{
    [Serializable]
    public class ApplyLinkWrenchResponse : Message
    {
        public const string k_RosMessageName = "simulation_extra_interfaces/ApplyLinkWrench";
        public override string RosMessageName => k_RosMessageName;

        //  Result codes follow simulation_interfaces/Result semantics.
        public const byte RESULT_OK = 1;
        public const byte RESULT_NOT_FOUND = 2; //  entity or link not found
        public const byte RESULT_OPERATION_FAILED = 4;
        public byte result;
        public string error_message;

        public ApplyLinkWrenchResponse()
        {
            this.result = 0;
            this.error_message = "";
        }

        public ApplyLinkWrenchResponse(byte result, string error_message)
        {
            this.result = result;
            this.error_message = error_message;
        }

        public static ApplyLinkWrenchResponse Deserialize(MessageDeserializer deserializer) => new ApplyLinkWrenchResponse(deserializer);

        private ApplyLinkWrenchResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
            deserializer.Read(out this.error_message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.error_message);
        }

        public override string ToString()
        {
            return "ApplyLinkWrenchResponse: " +
            "\nresult: " + result.ToString() +
            "\nerror_message: " + error_message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
