//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationExtraInterfaces
{
    [Serializable]
    public class ApplyLinkWrenchRequest : Message
    {
        public const string k_RosMessageName = "simulation_extra_interfaces/ApplyLinkWrench";
        public override string RosMessageName => k_RosMessageName;

        //  Apply a constant wrench to a link of a spawned entity, expressed in the
        //  world frame with ROS axis conventions (x forward, y left, z up).
        //  The force is applied at the link's center of mass every physics step for
        //  `duration` simulated seconds (0 = exactly one physics step). Time is counted
        //  in simulation steps, so the behaviour is identical under time_scale and
        //  step_simulation. Calling again for the same link adds another wrench;
        //  reset_simulation clears all active wrenches.
        public string entity;
        //  entity name as listed by get_entities
        public string link;
        //  link name; empty targets the base link
        public Geometry.WrenchMsg wrench;
        //  force [N] and torque [N m], world frame
        public double duration;
        //  simulated seconds; 0 = one physics step

        public ApplyLinkWrenchRequest()
        {
            this.entity = "";
            this.link = "";
            this.wrench = new Geometry.WrenchMsg();
            this.duration = 0.0;
        }

        public ApplyLinkWrenchRequest(string entity, string link, Geometry.WrenchMsg wrench, double duration)
        {
            this.entity = entity;
            this.link = link;
            this.wrench = wrench;
            this.duration = duration;
        }

        public static ApplyLinkWrenchRequest Deserialize(MessageDeserializer deserializer) => new ApplyLinkWrenchRequest(deserializer);

        private ApplyLinkWrenchRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.entity);
            deserializer.Read(out this.link);
            this.wrench = Geometry.WrenchMsg.Deserialize(deserializer);
            deserializer.Read(out this.duration);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.entity);
            serializer.Write(this.link);
            serializer.Write(this.wrench);
            serializer.Write(this.duration);
        }

        public override string ToString()
        {
            return "ApplyLinkWrenchRequest: " +
            "\nentity: " + entity.ToString() +
            "\nlink: " + link.ToString() +
            "\nwrench: " + wrench.ToString() +
            "\nduration: " + duration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
