//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationExtraInterfaces
{
    [Serializable]
    public class GetContactEventsRequest : Message
    {
        public const string k_RosMessageName = "simulation_extra_interfaces/GetContactEvents";
        public override string RosMessageName => k_RosMessageName;

        //  Query the collision records accumulated for spawned entities.
        //  Every link of every spawned entity is monitored; records aggregate per
        //  (entity, link, other object). Wheels resting on the floor produce records
        //  with other == "Plane" (the built-in floor) — filter by `other` on the
        //  caller side to ignore expected contacts.
        //  reset_simulation with SCOPE_STATE clears all records.
        public string entity;
        //  empty = records of every entity
        public bool clear;
        //  true = clear the returned records after reading

        public GetContactEventsRequest()
        {
            this.entity = "";
            this.clear = false;
        }

        public GetContactEventsRequest(string entity, bool clear)
        {
            this.entity = entity;
            this.clear = clear;
        }

        public static GetContactEventsRequest Deserialize(MessageDeserializer deserializer) => new GetContactEventsRequest(deserializer);

        private GetContactEventsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.entity);
            deserializer.Read(out this.clear);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.entity);
            serializer.Write(this.clear);
        }

        public override string ToString()
        {
            return "GetContactEventsRequest: " +
            "\nentity: " + entity.ToString() +
            "\nclear: " + clear.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
