//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationExtraInterfaces
{
    [Serializable]
    public class GetContactEventsResponse : Message
    {
        public const string k_RosMessageName = "simulation_extra_interfaces/GetContactEvents";
        public override string RosMessageName => k_RosMessageName;

        public const byte RESULT_OK = 1;
        public const byte RESULT_OPERATION_FAILED = 4;
        public byte result;
        public string error_message;
        public ContactRecordMsg[] contacts;

        public GetContactEventsResponse()
        {
            this.result = 0;
            this.error_message = "";
            this.contacts = new ContactRecordMsg[0];
        }

        public GetContactEventsResponse(byte result, string error_message, ContactRecordMsg[] contacts)
        {
            this.result = result;
            this.error_message = error_message;
            this.contacts = contacts;
        }

        public static GetContactEventsResponse Deserialize(MessageDeserializer deserializer) => new GetContactEventsResponse(deserializer);

        private GetContactEventsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
            deserializer.Read(out this.error_message);
            deserializer.Read(out this.contacts, ContactRecordMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.error_message);
            serializer.WriteLength(this.contacts);
            serializer.Write(this.contacts);
        }

        public override string ToString()
        {
            return "GetContactEventsResponse: " +
            "\nresult: " + result.ToString() +
            "\nerror_message: " + error_message.ToString() +
            "\ncontacts: " + System.String.Join(", ", contacts.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
