//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationExtraInterfaces
{
    [Serializable]
    public class StepAndObserveResponse : Message
    {
        public const string k_RosMessageName = "simulation_extra_interfaces/StepAndObserve";
        public override string RosMessageName => k_RosMessageName;

        //  Result codes follow simulation_interfaces/Result semantics.
        public const byte RESULT_OK = 1;
        public const byte RESULT_NOT_FOUND = 2; //  entity not found, or it has no joint state publisher
        public const byte RESULT_INCORRECT_STATE = 3; //  no world loaded
        public const byte RESULT_OPERATION_FAILED = 4; //  not paused, another step running, steps too large
        public byte result;
        public string error_message;
        public Sensor.JointStateMsg joint_states;
        //  every joint of the entity after the steps; velocity is
        //  the position difference over the stepped time (0 when
        //  steps = 0 or on the first call for an entity)
        public double sim_time;
        //  simulation time [s] after the steps

        public StepAndObserveResponse()
        {
            this.result = 0;
            this.error_message = "";
            this.joint_states = new Sensor.JointStateMsg();
            this.sim_time = 0.0;
        }

        public StepAndObserveResponse(byte result, string error_message, Sensor.JointStateMsg joint_states, double sim_time)
        {
            this.result = result;
            this.error_message = error_message;
            this.joint_states = joint_states;
            this.sim_time = sim_time;
        }

        public static StepAndObserveResponse Deserialize(MessageDeserializer deserializer) => new StepAndObserveResponse(deserializer);

        private StepAndObserveResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
            deserializer.Read(out this.error_message);
            this.joint_states = Sensor.JointStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.sim_time);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.error_message);
            serializer.Write(this.joint_states);
            serializer.Write(this.sim_time);
        }

        public override string ToString()
        {
            return "StepAndObserveResponse: " +
            "\nresult: " + result.ToString() +
            "\nerror_message: " + error_message.ToString() +
            "\njoint_states: " + joint_states.ToString() +
            "\nsim_time: " + sim_time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
