//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationExtraInterfaces
{
    [Serializable]
    public class StepAndObserveRequest : Message
    {
        public const string k_RosMessageName = "simulation_extra_interfaces/StepAndObserve";
        public override string RosMessageName => k_RosMessageName;

        //  One round trip for a learning loop: apply a joint command to a spawned entity,
        //  advance the simulation by `steps` physics steps, and return the entity's joint
        //  state afterwards. Equivalent to publishing on the entity's joint_command topic,
        //  calling step_simulation, and reading joint_states, but without the topic
        //  latency and with no ambiguity about which state belongs to which step.
        // 
        //  The simulation must be PAUSED (same rule as step_simulation). The entity must
        //  carry <ros2_control> (that is what gives it joint state publishers). The
        //  command has the semantics of the joint_command topic: joints are matched by
        //  name, position/velocity target the drive (or the servo model), effort drives
        //  effort-mode joints. An empty name[] applies no command. steps = 0 only observes.
        public string entity;
        //  entity name as returned by spawn_entity
        public ulong steps;
        //  physics steps to run (0 = observe only)
        public Sensor.JointStateMsg command;
        //  optional joint command, applied before stepping

        public StepAndObserveRequest()
        {
            this.entity = "";
            this.steps = 0;
            this.command = new Sensor.JointStateMsg();
        }

        public StepAndObserveRequest(string entity, ulong steps, Sensor.JointStateMsg command)
        {
            this.entity = entity;
            this.steps = steps;
            this.command = command;
        }

        public static StepAndObserveRequest Deserialize(MessageDeserializer deserializer) => new StepAndObserveRequest(deserializer);

        private StepAndObserveRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.entity);
            deserializer.Read(out this.steps);
            this.command = Sensor.JointStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.entity);
            serializer.Write(this.steps);
            serializer.Write(this.command);
        }

        public override string ToString()
        {
            return "StepAndObserveRequest: " +
            "\nentity: " + entity.ToString() +
            "\nsteps: " + steps.ToString() +
            "\ncommand: " + command.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
