//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationExtraInterfaces
{
    [Serializable]
    public class ContactRecordMsg : Message
    {
        public const string k_RosMessageName = "simulation_extra_interfaces/ContactRecord";
        public override string RosMessageName => k_RosMessageName;

        //  Aggregated contact record between an entity link and one other object,
        //  accumulated since the last reset (or explicit clear).
        public string entity;
        //  entity whose link touched something
        public string link;
        //  link name
        public string other;
        //  the other party: another entity's name, or the scenery
        //  object's name (the built-in floor is "Plane")
        public uint count;
        //  number of contact-begin events
        public double first_time;
        //  simulation time [s] of the first contact
        public double last_time;
        //  simulation time [s] of the most recent contact
        public double max_impulse;
        //  largest contact impulse magnitude seen [N s]

        public ContactRecordMsg()
        {
            this.entity = "";
            this.link = "";
            this.other = "";
            this.count = 0;
            this.first_time = 0.0;
            this.last_time = 0.0;
            this.max_impulse = 0.0;
        }

        public ContactRecordMsg(string entity, string link, string other, uint count, double first_time, double last_time, double max_impulse)
        {
            this.entity = entity;
            this.link = link;
            this.other = other;
            this.count = count;
            this.first_time = first_time;
            this.last_time = last_time;
            this.max_impulse = max_impulse;
        }

        public static ContactRecordMsg Deserialize(MessageDeserializer deserializer) => new ContactRecordMsg(deserializer);

        private ContactRecordMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.entity);
            deserializer.Read(out this.link);
            deserializer.Read(out this.other);
            deserializer.Read(out this.count);
            deserializer.Read(out this.first_time);
            deserializer.Read(out this.last_time);
            deserializer.Read(out this.max_impulse);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.entity);
            serializer.Write(this.link);
            serializer.Write(this.other);
            serializer.Write(this.count);
            serializer.Write(this.first_time);
            serializer.Write(this.last_time);
            serializer.Write(this.max_impulse);
        }

        public override string ToString()
        {
            return "ContactRecordMsg: " +
            "\nentity: " + entity.ToString() +
            "\nlink: " + link.ToString() +
            "\nother: " + other.ToString() +
            "\ncount: " + count.ToString() +
            "\nfirst_time: " + first_time.ToString() +
            "\nlast_time: " + last_time.ToString() +
            "\nmax_impulse: " + max_impulse.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
