//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationExtraInterfaces
{
    [Serializable]
    public class GnssSolutionMsg : Message
    {
        public const string k_RosMessageName = "simulation_extra_interfaces/GnssSolution";
        public override string RosMessageName => k_RosMessageName;

        //  The solution a simulated GNSS receiver produced, and why.
        //  sensor_msgs/NavSatFix cannot distinguish an RTK FIXED solution from an RTK
        //  FLOAT one; this carries what it cannot.
        public const byte STATE_NO_FIX = 0;
        public const byte STATE_SINGLE = 1;
        public const byte STATE_FLOAT = 2;
        public const byte STATE_FIX = 3;
        public Std.HeaderMsg header;
        public byte state;
        public byte usable_satellites;
        public byte nlos_satellites;
        public byte locked_satellites;
        public float hdop;
        public float pdop;
        public float horizontal_sigma;
        public float error_east;
        public float error_north;
        public float nlos_east;
        public float nlos_north;
        public bool wrong_fix;
        public float wrong_fix_east;
        public float wrong_fix_north;

        public GnssSolutionMsg()
        {
            this.header = new Std.HeaderMsg();
            this.state = 0;
            this.usable_satellites = 0;
            this.nlos_satellites = 0;
            this.locked_satellites = 0;
            this.hdop = 0.0f;
            this.pdop = 0.0f;
            this.horizontal_sigma = 0.0f;
            this.error_east = 0.0f;
            this.error_north = 0.0f;
            this.nlos_east = 0.0f;
            this.nlos_north = 0.0f;
            this.wrong_fix = false;
            this.wrong_fix_east = 0.0f;
            this.wrong_fix_north = 0.0f;
        }

        public GnssSolutionMsg(Std.HeaderMsg header, byte state, byte usable_satellites, byte nlos_satellites, byte locked_satellites, float hdop, float pdop, float horizontal_sigma, float error_east, float error_north, float nlos_east, float nlos_north, bool wrong_fix, float wrong_fix_east, float wrong_fix_north)
        {
            this.header = header;
            this.state = state;
            this.usable_satellites = usable_satellites;
            this.nlos_satellites = nlos_satellites;
            this.locked_satellites = locked_satellites;
            this.hdop = hdop;
            this.pdop = pdop;
            this.horizontal_sigma = horizontal_sigma;
            this.error_east = error_east;
            this.error_north = error_north;
            this.nlos_east = nlos_east;
            this.nlos_north = nlos_north;
            this.wrong_fix = wrong_fix;
            this.wrong_fix_east = wrong_fix_east;
            this.wrong_fix_north = wrong_fix_north;
        }

        public static GnssSolutionMsg Deserialize(MessageDeserializer deserializer) => new GnssSolutionMsg(deserializer);

        private GnssSolutionMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.state);
            deserializer.Read(out this.usable_satellites);
            deserializer.Read(out this.nlos_satellites);
            deserializer.Read(out this.locked_satellites);
            deserializer.Read(out this.hdop);
            deserializer.Read(out this.pdop);
            deserializer.Read(out this.horizontal_sigma);
            deserializer.Read(out this.error_east);
            deserializer.Read(out this.error_north);
            deserializer.Read(out this.nlos_east);
            deserializer.Read(out this.nlos_north);
            deserializer.Read(out this.wrong_fix);
            deserializer.Read(out this.wrong_fix_east);
            deserializer.Read(out this.wrong_fix_north);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.state);
            serializer.Write(this.usable_satellites);
            serializer.Write(this.nlos_satellites);
            serializer.Write(this.locked_satellites);
            serializer.Write(this.hdop);
            serializer.Write(this.pdop);
            serializer.Write(this.horizontal_sigma);
            serializer.Write(this.error_east);
            serializer.Write(this.error_north);
            serializer.Write(this.nlos_east);
            serializer.Write(this.nlos_north);
            serializer.Write(this.wrong_fix);
            serializer.Write(this.wrong_fix_east);
            serializer.Write(this.wrong_fix_north);
        }

        public override string ToString()
        {
            return "GnssSolutionMsg: " +
            "\nheader: " + header.ToString() +
            "\nstate: " + state.ToString() +
            "\nusable_satellites: " + usable_satellites.ToString() +
            "\nnlos_satellites: " + nlos_satellites.ToString() +
            "\nlocked_satellites: " + locked_satellites.ToString() +
            "\nhdop: " + hdop.ToString() +
            "\npdop: " + pdop.ToString() +
            "\nhorizontal_sigma: " + horizontal_sigma.ToString() +
            "\nerror_east: " + error_east.ToString() +
            "\nerror_north: " + error_north.ToString() +
            "\nnlos_east: " + nlos_east.ToString() +
            "\nnlos_north: " + nlos_north.ToString() +
            "\nwrong_fix: " + wrong_fix.ToString() +
            "\nwrong_fix_east: " + wrong_fix_east.ToString() +
            "\nwrong_fix_north: " + wrong_fix_north.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
