//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationExtraInterfaces
{
    [Serializable]
    public class GnssSkyViewMsg : Message
    {
        public const string k_RosMessageName = "simulation_extra_interfaces/GnssSkyView";
        public override string RosMessageName => k_RosMessageName;

        //  What a GNSS antenna can see of the sky at its current position, computed by
        //  ray tracing the scene rather than by modelling a receiver.
        // 
        //  This is deliberately the GEOMETRY only: which satellites reach the antenna and
        //  how. Turning that into a fix grade (RTK fix / float / single), a pseudorange
        //  error and a position is the consumer's job -- in this project, the GPS emulator
        //  on the ROS side. Keeping the split here means the decision logic can be tuned
        //  and unit-tested without rebuilding the simulator.
        public Std.HeaderMsg header;
        public byte usable_satellites;
        //  satellites with a direct line of sight above the mask
        public float hdop;
        //  horizontal dilution of precision of that set
        public float pdop;
        //  position dilution of precision of that set
        public GnssSatelliteMsg[] satellites;
        //  every tracked satellite, usable or not

        public GnssSkyViewMsg()
        {
            this.header = new Std.HeaderMsg();
            this.usable_satellites = 0;
            this.hdop = 0.0f;
            this.pdop = 0.0f;
            this.satellites = new GnssSatelliteMsg[0];
        }

        public GnssSkyViewMsg(Std.HeaderMsg header, byte usable_satellites, float hdop, float pdop, GnssSatelliteMsg[] satellites)
        {
            this.header = header;
            this.usable_satellites = usable_satellites;
            this.hdop = hdop;
            this.pdop = pdop;
            this.satellites = satellites;
        }

        public static GnssSkyViewMsg Deserialize(MessageDeserializer deserializer) => new GnssSkyViewMsg(deserializer);

        private GnssSkyViewMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.usable_satellites);
            deserializer.Read(out this.hdop);
            deserializer.Read(out this.pdop);
            deserializer.Read(out this.satellites, GnssSatelliteMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.usable_satellites);
            serializer.Write(this.hdop);
            serializer.Write(this.pdop);
            serializer.WriteLength(this.satellites);
            serializer.Write(this.satellites);
        }

        public override string ToString()
        {
            return "GnssSkyViewMsg: " +
            "\nheader: " + header.ToString() +
            "\nusable_satellites: " + usable_satellites.ToString() +
            "\nhdop: " + hdop.ToString() +
            "\npdop: " + pdop.ToString() +
            "\nsatellites: " + System.String.Join(", ", satellites.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
