//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationExtraInterfaces
{
    [Serializable]
    public class GnssSatelliteMsg : Message
    {
        public const string k_RosMessageName = "simulation_extra_interfaces/GnssSatellite";
        public override string RosMessageName => k_RosMessageName;

        //  One satellite as seen from a GNSS antenna in the simulator, after ray tracing
        //  the line of sight against the scene geometry.
        // 
        //  Angles follow the usual GNSS convention in the ENU frame the simulator's world
        //  is expressed in: azimuth is measured from North towards East, elevation from
        //  the local horizon.
        public const byte STATE_LOS = 0;
        public const byte STATE_BLOCKED = 1;
        public const byte STATE_NLOS = 2;
        public const byte STATE_BELOW_MASK = 3;
        public ushort prn;
        //  satellite identifier, stable for the whole run
        public float azimuth;
        //  [rad] from North towards East
        public float elevation;
        //  [rad] above the horizon
        public byte state;
        //  one of STATE_*
        public float excess_path_length;
        //  [m] extra path length of the reflected ray; 0 unless STATE_NLOS
        public float relative_power_db;
        //  [dB] relative to a clean direct signal; <= 0

        public GnssSatelliteMsg()
        {
            this.prn = 0;
            this.azimuth = 0.0f;
            this.elevation = 0.0f;
            this.state = 0;
            this.excess_path_length = 0.0f;
            this.relative_power_db = 0.0f;
        }

        public GnssSatelliteMsg(ushort prn, float azimuth, float elevation, byte state, float excess_path_length, float relative_power_db)
        {
            this.prn = prn;
            this.azimuth = azimuth;
            this.elevation = elevation;
            this.state = state;
            this.excess_path_length = excess_path_length;
            this.relative_power_db = relative_power_db;
        }

        public static GnssSatelliteMsg Deserialize(MessageDeserializer deserializer) => new GnssSatelliteMsg(deserializer);

        private GnssSatelliteMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.prn);
            deserializer.Read(out this.azimuth);
            deserializer.Read(out this.elevation);
            deserializer.Read(out this.state);
            deserializer.Read(out this.excess_path_length);
            deserializer.Read(out this.relative_power_db);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.prn);
            serializer.Write(this.azimuth);
            serializer.Write(this.elevation);
            serializer.Write(this.state);
            serializer.Write(this.excess_path_length);
            serializer.Write(this.relative_power_db);
        }

        public override string ToString()
        {
            return "GnssSatelliteMsg: " +
            "\nprn: " + prn.ToString() +
            "\nazimuth: " + azimuth.ToString() +
            "\nelevation: " + elevation.ToString() +
            "\nstate: " + state.ToString() +
            "\nexcess_path_length: " + excess_path_length.ToString() +
            "\nrelative_power_db: " + relative_power_db.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
