//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SimulationExtraInterfaces
{
    [Serializable]
    public class MagneticGuideMsg : Message
    {
        public const string k_RosMessageName = "simulation_extra_interfaces/MagneticGuide";
        public override string RosMessageName => k_RosMessageName;

        //  Reading of a magnetic guide (line) sensor of the AGV kind (Roboteq MGS1600,
        //  Accurate UDS-1213): where the magnetic tape lies under the sensor bar, and
        //  markers of the opposite polarity beside it. Lateral positions are in metres,
        //  positive to the sensor's left (ROS +y of the sensor frame), zero at its centre.
        public Std.HeaderMsg header;
        public bool track_detected;
        //  a track-polarity tape is under the bar
        public float position;
        //  lateral position of the selected track [m], +left; 0 when none
        public bool left_marker;
        //  marker-polarity tape left of the (selected) track
        public bool right_marker;
        //  marker-polarity tape right of the (selected) track
        public float[] track_positions;
        //  every track under the bar, left to right (a fork shows two)

        public MagneticGuideMsg()
        {
            this.header = new Std.HeaderMsg();
            this.track_detected = false;
            this.position = 0.0f;
            this.left_marker = false;
            this.right_marker = false;
            this.track_positions = new float[0];
        }

        public MagneticGuideMsg(Std.HeaderMsg header, bool track_detected, float position, bool left_marker, bool right_marker, float[] track_positions)
        {
            this.header = header;
            this.track_detected = track_detected;
            this.position = position;
            this.left_marker = left_marker;
            this.right_marker = right_marker;
            this.track_positions = track_positions;
        }

        public static MagneticGuideMsg Deserialize(MessageDeserializer deserializer) => new MagneticGuideMsg(deserializer);

        private MagneticGuideMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.track_detected);
            deserializer.Read(out this.position);
            deserializer.Read(out this.left_marker);
            deserializer.Read(out this.right_marker);
            deserializer.Read(out this.track_positions, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.track_detected);
            serializer.Write(this.position);
            serializer.Write(this.left_marker);
            serializer.Write(this.right_marker);
            serializer.WriteLength(this.track_positions);
            serializer.Write(this.track_positions);
        }

        public override string ToString()
        {
            return "MagneticGuideMsg: " +
            "\nheader: " + header.ToString() +
            "\ntrack_detected: " + track_detected.ToString() +
            "\nposition: " + position.ToString() +
            "\nleft_marker: " + left_marker.ToString() +
            "\nright_marker: " + right_marker.ToString() +
            "\ntrack_positions: " + System.String.Join(", ", track_positions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
